/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIpresentacion;

import java.awt.Frame;
import java.awt.Menu;
import java.awt.MenuBar;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
//import logica.Commando;
import java.awt.FileDialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import logica.BotonCentro;
import logica.BotonDerecha;
import logica.BotonIzquierda;
import logica.BtnRedCommand;
import logica.Command;

//import logica.Command;

/**
 *
 * @author gabriel
 */

public class GUISistema extends javax.swing.JFrame implements ActionListener {
    //Command cm;

BotonIzquierda bt;
BotonDerecha bd;
BotonCentro bc;

   

   public GUISistema() {
        initComponents();
        
           addWindowListener( new WindowAdapter() {
    	 public void windowClosing( WindowEvent e ) {
    		 System.exit(0);
    	 }
     } );
        
     
        bt=new BotonIzquierda("Izquierda",this);
        bc=new BotonCentro("Centro",this);
        bd=new BotonDerecha("Derecha",this);
  
        bt.setBounds(5,5, 100, 30);
        bc.setBounds(105,5, 100, 30);
        bd.setBounds(205,5, 100, 30);
    
        
      //  izquierdo.addActionListener(this);
//        this.repaint();
       
//    btnRed.addActionListener(this);
//    setBounds(100, 100, 200, 100);
//        izquierdo.setBounds(izquierdo.getBounds());
    bt.addActionListener(this);  
    bt.setVisible(true);
    bc.addActionListener(this);  
    bc.setVisible(true);
    bd.addActionListener(this);  
    bd.setVisible(true);
    add(bt);
//    bt.requestFocus();
    add(bc);
//    bc.requestFocus();
    add(bd);
//    bd.requestFocus();
    
    }
     public void actionPerformed(ActionEvent e) {
         System.out.println("asdasdasdas");
    Command obj = (Command) e.getSource();
    obj.Execute();
  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        titulo_ppal = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gUINuevaPlanillaIncripcion1 = new GUIpresentacion.GUINuevaPlanillaIncripcion();
        gUIInformeAltasBajas1 = new GUIpresentacion.GUIInformeAltasBajas();
        gUIInicioJuicio1 = new GUIpresentacion.GUIInicioJuicio();
        gUIConsultaAportes1 = new GUIpresentacion.GUIConsultaAportes();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo_ppal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo_ppal.setText("Sistema Caja Forense");

        jScrollPane1.setViewportView(gUINuevaPlanillaIncripcion1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Nueva Solicitud de Incripcion", jPanel1);
        jTabbedPane1.addTab("Informe de Altas y Bajas", gUIInformeAltasBajas1);
        jTabbedPane1.addTab("Inicio de Juicio", gUIInicioJuicio1);
        jTabbedPane1.addTab("Consulta de Aportes", gUIConsultaAportes1);

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_ppal, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_ppal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
       

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
  ///ASPECTO GRAFICO/////////////////////////////////////
       try { 
            UIManager.setLookAndFeel( 
              "javax.swing.plaf.metal.MetalLookAndFeel"
            ); 
        } catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e ) { }
     ///////////////////////////////////////////////////////
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Principal;
    private GUIpresentacion.GUIConsultaAportes gUIConsultaAportes1;
    private GUIpresentacion.GUIInformeAltasBajas gUIInformeAltasBajas1;
    private GUIpresentacion.GUIInicioJuicio gUIInicioJuicio1;
    private GUIpresentacion.GUINuevaPlanillaIncripcion gUINuevaPlanillaIncripcion1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel titulo_ppal;
    // End of variables declaration//GEN-END:variables

 
}
